version: '3.8'
services:
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_dbms_connector_bolt_advertised__address: 0.0.0.0:7687
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:0.74.0
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./infra/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "4317:4317" # OTLP gRPC receiver

  grafana:
    image: grafana/grafana:9
    ports:
      - "3000:3000"

volumes:
  neo4j_data:
