apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faiss-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # Optionally set storageClassName if your cluster requires it
# storageClassName: standard
